# Setup
title: Dark Poole
url: https://getpoole.com
baseurl: "/blog"
paginate: 1
permalink: /blog/:title/

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

  include:
  - blog/_sass


sass:
  sass_dir: blog
  style: compressed
  include_paths:
    - blog/_sass


# Google Analytics (Optional)
# Uncomment and replace to enable tracking
# ga_analytics: UA-000000-0

# Author details
author:
  name: Mark Otto
  url: https://twitter.com/mdo
  email: markdotto@gmail.com

# Custom variables
version: 3.0.0

# Navbar page list (relative to /blog/)
nav:
  - title: Blog
    url: /blog/archive

  - title: About
    url: /blog/about

# Pagination path under /blog/
paginate_path: "/blog/page:num/"
